# Generated by Django 3.0.6 on 2020-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='point',
        ),
        migrations.AddField(
            model_name='point',
            name='item',
            field=models.ManyToManyField(related_name='point_items', to='api.Item'),
        ),
    ]
