# Generated by Django 3.0.6 on 2020-06-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200602_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
