# Generated by Django 3.0.7 on 2020-06-06 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200603_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
