# Generated by Django 3.0.7 on 2020-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_point_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
