# Generated by Django 3.0.7 on 2020-06-07 22:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200607_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
